CREATE TABLE Anime(
	anime_id int PRIMARY KEY,
	title text,
	title_english text,
	title_japanese text,
	title_synonyms text,
	image_url text,
	type varchar(10),
	source varchar(100),
	episodes int,
	status varchar(100),
	airing varchar(5),
	aired_string text,
	aired text,
	duration text,
	rating text,
	score float,
	scored_by int,
	rank float,
	popularity int,
	members int,
	favorites int,
	background text,
	premiered text,
	broadcast text,
	related text,
	licensor text,
	producer text,
	studio text,
	genre text,
	opening_theme text,
	ending_theme text,
	duration_min float,
	aired_from_year float
);
